Update deploy-app-staging.yml

diff --git a/.github/workflows/deploy-app-staging.yml b/.github/workflows/deploy-app-staging.yml
--- a/.github/workflows/deploy-app-staging.yml
+++ b/.github/workflows/deploy-app-staging.yml
@@ -26,23 +26,23 @@ jobs:
         id: extract-version
         shell: bash
         run: |
-            TITLE = "${{ github.event.milestone.title }}"
-            echo "Milestone title: $TITLE"
-            
-            if [[ "$TITLE" =~ ^Customer\ v([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
-              VERSION="${BASH_REMATCH[1]}"
-              echo "Valid format detected: $VERSION"
-              echo "version=$VERSION" >> $GITHUB_ENV
-              echo "version=$VERSION" >> $GITHUB_OUTPUT
-              echo "is_valid=true" >> $GITHUB_ENV
-              echo "is_valid=true" >> $GITHUB_OUTPUT
-            else
-              echo "Invalid milestone format. Skipping..."
-              echo "is_valid=false" >> $GITHUB_ENV
-              echo "is_valid=false" >> $GITHUB_OUTPUT
-              exit 1
-            fi    
-    
+          TITLE="${{ github.event.milestone.title }}"
+          echo "Milestone title: $TITLE"
+          
+          if [[ "$TITLE" =~ ^Customer\ v([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
+            VERSION="${BASH_REMATCH[1]}"
+            echo "Valid format detected: $VERSION"
+            echo "version=$VERSION" >> $GITHUB_ENV
+            echo "version=$VERSION" >> $GITHUB_OUTPUT
+            echo "is_valid=true" >> $GITHUB_ENV
+            echo "is_valid=true" >> $GITHUB_OUTPUT
+          else
+            echo "Invalid milestone format. Skipping..."
+            echo "is_valid=false" >> $GITHUB_ENV
+            echo "is_valid=false" >> $GITHUB_OUTPUT
+            exit 1
+          fi
+          
   build-and-deploy:
     needs: check-milestone
     if: needs.check-milestone.outputs.is_valid == 'true'
